version: "3"

services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #   volumes:
  #     - draw-pg-data:/var/lib/postgresql/data

  draw-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3729:3729"
# Volumes for the database and redis
# volumes:
#   draw-pg-data:
